spring.application.name=stripe-provider-service
spring.profiles.active=@spring.profiles.active@
mytestkey=This value is from default properties file
server.port=8083

stripe.api.key=
stripe.create.session.url=https://api.stripe.com/v1/checkout/sessions